### ISSUE TITLE
Autoresponders

### ISSUE THREAD

**Issue by ewistrand** [AllClients/Api-Php-Examples#1]
Could you create a sample for the autoresponder? I've successfully set up and submitted new contacts but I need an autoresponder for each submission via the api. Thanks!

**Comment by toddbinder** [comment]
Hi there!   Glad you got going with the contacts.

Unfortunately we can't provide samples for every function (at this time).

The process is very similar to the AddContact process, you just need to use the AssignAutoresponder function: 

http://developers.allclients.com/api/contact/other/assignautoresponder/

However, if you are just adding the contact via the API, you will first need to set the contact's opt-in status to OPT IN (Value: 1)

http://developers.allclients.com/api/email/email/setoptinstatus/

Be sure to understand our SPAM policies first:    http://www.allclients.com/SpamPolicy.aspx
